Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,9 +28,10 @@ jobs:
             git config --global --add safe.directory /home/ubuntu/hello-world &&
             cd /home/ubuntu/hello-world &&
             git pull &&
-            docker-compose up -d
+            if [ -f docker-compose.yml ]; then
+              docker-compose up -d
+            else
+              echo 'Configuration file docker-compose.yml not found.'
+              exit 1
+            fi
           "
-
-
-
-        
